public import Foundation
public import Organizing
public import Reminders
public import StructuredQueries
public import Tagged

extension Reminders.Reminder {
    @Table("reminders")
    public struct Record: Identifiable, Hashable, Sendable {
        public let id: Reminder.ID
        public var listID: List<Reminder>.ID
        public var title = ""
        public var notes = ""
        @Column("due")
        public var dueDate: Date?
        public var hasTime = false
        public var flagged = false
        public var priority: Reminder.Priority?
        public var status: Status = .incomplete
        public var position = 0
        public var location: Reminder.Location?
        public var repeats: Reminder.Repeat = .never
        public var created: Date

        public init(
            id: Reminder.ID,
            listID: List<Reminder>.ID,
            title: String = "",
            notes: String = "",
            dueDate: Date? = nil,
            hasTime: Bool = false,
            flagged: Bool = false,
            priority: Reminder.Priority? = nil,
            status: Status = .incomplete,
            position: Int = 0,
            location: Reminder.Location? = nil,
            repeats: Reminder.Repeat = .never,
            created: Date
        ) {
            self.id = id
            self.listID = listID
            self.title = title
            self.notes = notes
            self.dueDate = dueDate
            self.hasTime = hasTime
            self.flagged = flagged
            self.priority = priority
            self.status = status
            self.position = position
            self.location = location
            self.repeats = repeats
            self.created = created
        }
    }
}

// The draft is generated by `@Table` in this file, and these conformances can only be synthesised here.
extension Reminders.Reminder.Record.Draft: Hashable, Sendable {}

extension Reminders.Reminder.Record {
    public static func toggle(_ id: Reminder.ID) -> UpdateOf<Reminder.Record> {
        Reminder.Record.find(id).update {
            $0.status = Case($0.status).when(.incomplete, then: .pending).else(.incomplete)
        }
    }

    public static var completePending: UpdateOf<Reminder.Record> {
        Reminder.Record.where { $0.isPending }.update { $0.status = .completed }
    }

    public static func placeLast(_ id: Reminder.ID) -> UpdateOf<Reminder.Record> {
        Reminder.Record.find(id).update { $0.position = Reminder.Record.select { ($0.position.max() ?? -1) + 1 } }
    }

    public static func makeRoom(after position: Int) -> UpdateOf<Reminder.Record> {
        Reminder.Record.where { $0.position.gt(position) }.update { $0.position += 1 }
    }

    public static func changes(from original: Reminder, to draft: Reminder) -> UpdateOf<Reminder.Record>? {
        var same = original
        same.completion = draft.completion
        same.tags = draft.tags
        guard same != draft else { return nil }
        return Reminder.Record.find(original.id).update { row in
            if draft.list != original.list { row.listID = draft.list }
            if draft.title != original.title { row.title = draft.title }
            if draft.notes != original.notes { row.notes = draft.notes }
            if draft.due != original.due {
                row.dueDate = draft.due?.date
                row.hasTime = draft.due?.hasTime ?? false
            }
            if draft.flagged != original.flagged { row.flagged = draft.flagged }
            if draft.priority != original.priority { row.priority = draft.priority }
            if draft.position != original.position { row.position = draft.position }
            if draft.location != original.location { row.location = draft.location }
            if draft.repeats != original.repeats { row.repeats = draft.repeats }
        }
    }

    public static func deleteCompleted(in filter: Reminders.Filter, today: Range<Date>) -> DeleteOf<Reminder.Record> {
        Reminder.Record.where { $0.isDone && $0.belongs(to: filter, today: today) }.delete()
    }
}
