public import Foundation
public import Organizing
public import Reminders
public import StructuredQueries
public import Tagged

extension Reminders.Reminder {
    @Table("reminders")
    public struct Record: Identifiable, Hashable, Sendable {
        public let id: Reminder.ID
        public var listID: List<Reminder>.ID
        public var title = ""
        public var notes = ""
        @Column("due")
        public var dueDate: Date?
        public var hasTime = false
        public var flagged = false
        public var priority: Reminder.Priority?
        public var status: Status = .incomplete
        public var position = 0
        public var location: Reminder.Location?
        public var repeats: Reminder.Repeat = .never
        public var created: Date

        public init(
            id: Reminder.ID,
            listID: List<Reminder>.ID,
            title: String = "",
            notes: String = "",
            dueDate: Date? = nil,
            hasTime: Bool = false,
            flagged: Bool = false,
            priority: Reminder.Priority? = nil,
            status: Status = .incomplete,
            position: Int = 0,
            location: Reminder.Location? = nil,
            repeats: Reminder.Repeat = .never,
            created: Date
        ) {
            self.id = id
            self.listID = listID
            self.title = title
            self.notes = notes
            self.dueDate = dueDate
            self.hasTime = hasTime
            self.flagged = flagged
            self.priority = priority
            self.status = status
            self.position = position
            self.location = location
            self.repeats = repeats
            self.created = created
        }
    }
}

// The draft is generated by `@Table` in this file, and these conformances can only be synthesised here.
extension Reminders.Reminder.Record.Draft: Hashable, Sendable {}

extension Reminders.Reminder.Record {
    public static func toggle(_ id: Reminder.ID) -> UpdateOf<Reminder.Record> {
        Reminder.Record.find(id).update {
            $0.status = Case($0.status).when(.incomplete, then: .pending).else(.incomplete)
        }
    }

    public static var completePending: UpdateOf<Reminder.Record> {
        Reminder.Record.where { $0.isPending }.update { $0.status = .completed }
    }

    public static func placeLast(_ id: Reminder.ID) -> UpdateOf<Reminder.Record> {
        Reminder.Record.find(id).update { $0.position = Reminder.Record.select { ($0.position.max() ?? -1) + 1 } }
    }

    public static func makeRoom(after position: Int) -> UpdateOf<Reminder.Record> {
        Reminder.Record.where { $0.position.gt(position) }.update { $0.position += 1 }
    }

    /// Writes the columns a form edits and never `status`, `position`, or `created`: a new draft
    /// is inserted, an existing one's form columns are replaced.
    public static func save(_ draft: Draft) -> InsertOf<Reminder.Record> {
        Reminder.Record.insert {
            draft
        } onConflict: {
            $0.id
        } doUpdate: { row, excluded in
            row.title = excluded.title
            row.notes = excluded.notes
            row.dueDate = excluded.dueDate
            row.hasTime = excluded.hasTime
            row.flagged = excluded.flagged
            row.priority = excluded.priority
            row.listID = excluded.listID
            row.location = excluded.location
            row.repeats = excluded.repeats
        }
    }

    public static func deleteCompleted(in filter: Reminders.Filter, today: Range<Date>) -> DeleteOf<Reminder.Record> {
        Reminder.Record.where { $0.isDone && $0.belongs(to: filter, today: today) }.delete()
    }
}
